### ISSUE TITLE
PowerShellOnLinux Logo

### ISSUE THREAD

**Issue by the-mentor** [adilio/ps-design#10]
Hi @adilio to follow up our conversation on twitter.
I'm looking for a logo for the [PowershellOnLinux](twitter.com/PoSH4Linux) twitter and telegram group.

I love your work and thank you very much for your time !!
-DM

**Comment by adilio** [comment]
Hey @the-mentor!

Happy to collab on something. What did you have in mind?

You'd need to provide some inspiration for the base of the idea. Fair warning, I may end up going in a totally different direction 🤣 , but I will try to work with whatever you had in mind.

Cheers! 🍻

**Comment by the-mentor** [comment]
At the moment i use this logo.
![image](https://user-images.githubusercontent.com/11185446/64480421-0fcce600-d1d0-11e9-956c-f0cfd0c90deb.png)
I want something with the Linux penguin since its about PowerShell for Linux and the PowerShell core/7 dark logo not the windows blue logo.
Other then that I don't have any idea but i want it to have a cool/wow factor.
Whatever you do I'm sure it will be amazing.

thanks a bunch.
-DM

**Comment by adilio** [comment]
Hi @the-mentor,

Apologies for the looong delay, I am finally back home, and in a position to start working on fun design projects again! 😄

I did see the _lovely_ design your Wife made for you, that one is VERY NICE! 😍 

I'm just following=up on this request, and again I'm very sorry for the long delay, as my work and personal life has been exceptionally crazy!

Are you still wanting to collaborate on this branding, or are you all set? More than happy to work with you on this now, as I have some time over the break.

Please let me know either way, and keep up the AWESOME work in the PowerShell Community! 💯

**Comment by the-mentor** [comment]
Hi @adilio thank you for reaching out.
I know you are really busy and can probably help other people get their logo design going. 
I'm quite happy with the logo my wife created for the PowershellOnLinux.com project. 

Keep up your awesome work!! 👏 
-DM

**Comment by adilio** [comment]
Awesome @the-mentor (DM), I appreciate your understanding, and again I really dig your Wife's logo! 😍

Just for fun last night, I did have a go at a sort of cute version of your legacy logo, using some stock logo templates from a site i have membership to.

I know you had mentioned before that you wanted to incorporate the PowerShell Core-ish logo, as it was more relevant to Linux.

Here's just something I was playing with. Let me know if you have feedback or ideas, as the creative juices appear to be flowing.

Cheers! 🍻 

![powershell-on-linux](https://user-images.githubusercontent.com/21287462/71187210-7764e980-2233-11ea-8b96-d904b01c5385.png)
