### ISSUE TITLE
PowerAruba logo

### ISSUE THREAD

**Issue by alagoutte** [adilio/ps-design#11]
Hi,

i have a GitHub Organization (https://www.github.com/PowerAruba) with multiple module ( PowerArubaCL, PowerArubaCP, PowerArubaCX, PowerubaIAP, PowerArubaMC, PowerArubaSW) about Aruba Product

I search to have a logo for PowerAruba Organisation with (small) variant for each module

There is "official" color for Aruba... Product => https://www.arubanetworks.com/fr/societe/media-center/

There is also some visio stencils available on visio cafe ( http://www.visiocafe.com/hpe.htm => HPE-Aruba-Symbols)
 
About module, each module is for type of product of 

- PowerArubaCL => Central (Cloud)
- PowerArubaCP => ClearPass
- PowerArubaCX => Aruba CX Switch
- PowerArubaIAP => Instant Access Point
- PowerArubaMC => Access Point / Mobility Controller
- PowerArubaSW => Aruba Switch

Merci d'avance !

**Comment by adilio** [comment]
Hi @alagoutte,

Apologies for the looong delay, I am _finally_ back home, and in a position to start working on fun design projects again! 😄 

If I understand correctly, you'd like one master logo, with variants for each product line?

Aruba, like any brand, can be a bit strict on the copyright of their own design, and may not take kindly to either using their branding directly, or editing their branding. Therefore, let me work on a design _inspired_ by theirs, and came back to you here in the next day or two with my first draft.

Bon?

**Comment by adilio** [comment]
Hi @alagoutte.

So, this is what the Aruba logo looks like:

![512px-Aruba_Networks_logo svg](https://user-images.githubusercontent.com/21287462/71152008-1664f380-21ea-11ea-861b-a4e9ec45f9cc.png)

The closest open source font I can get to this is **"Righteous"**, a Google font.

I decided to incorporate an antenna tower sending WiFi signal as the "A".

This is a first pass, but I really like the simplicity of it. Let me know what you think.

![poweraruba](https://user-images.githubusercontent.com/21287462/71152145-76f43080-21ea-11ea-9851-f436282f0434.png)

**Comment by alagoutte** [comment]
Nice !

but there is not only wireless but network ! 

and also i think, it will be a good idea also some PowerShell stuff

**Comment by alagoutte** [comment]
Hi,

![PowerAruba](https://user-images.githubusercontent.com/1098542/71381172-b77cf100-25d2-11ea-9d82-9f2823e9efc4.png)

Some icon available on Visio Stencil and i think, it will be nice to have on logo (with Powershell logo too)

**Comment by adilio** [comment]
HI @alagoutte, as mentioned before, I do NOT have access to a Visio install. If you can export the icons as an SVG, or other scalable vector format, that's great. Otherwise, I will tell you now that you will _definitnely_ not be able to shrink or grow the images without having quality issues. PNG will not work for this case, sorry.

**Comment by alagoutte** [comment]
[PowerAruba.zip](https://github.com/adilio/ps-design/files/3997286/PowerAruba.zip)

**Comment by adilio** [comment]
Thanks for that, @alagoutte !

So, am I right in assuming you would like a a unique logo for each module? Something like:

![poweraruba2](https://user-images.githubusercontent.com/21287462/71528828-a9f78d80-2896-11ea-902f-8db6031fd277.png)

If so, please help me by letting me know which logo belongs to which product. I realize some are self-explanatory, I just wanna be clear.

**Comment by alagoutte** [comment]
Hi @adilio 

With the name of each module with logo

![With Name](https://user-images.githubusercontent.com/1098542/71532255-d04b1680-28f2-11ea-82ad-944f8326dd7c.jpg)

Yes i like your idea ! may be also possible to have on the top Power in the middle the icon and on the botton ArubaXX ? 
or have Power using PowerShell style typo/logo ?

**Comment by adilio** [comment]
![PowerArubaCP](https://user-images.githubusercontent.com/21287462/75130966-b7a67500-5685-11ea-9d94-04360db0ecb8.png)
![PowerArubaCX](https://user-images.githubusercontent.com/21287462/75130968-b83f0b80-5685-11ea-91b3-beafe80b2190.png)
![PowerArubaIAP](https://user-images.githubusercontent.com/21287462/75130969-b8d7a200-5685-11ea-807b-a9f888c66c72.png)
![PowerArubaMC](https://user-images.githubusercontent.com/21287462/75130970-b8d7a200-5685-11ea-9598-df12b2b5828f.png)
![PowerArubaSW](https://user-images.githubusercontent.com/21287462/75130971-b8d7a200-5685-11ea-8967-ed54e6b9cad4.png)
![PowerArubaCL](https://user-images.githubusercontent.com/21287462/75130972-b9703880-5685-11ea-930c-a3ad7155e3fc.png)

**Comment by adilio** [comment]
Hi @alagoutte,

As we discussed, my work priorities have not allowed me much free time to work on these, but I am delivering these as promised.

Sorry again they are so late!

I took your idea of incorporating the logo's into the PowerAruba branding, and this is my interpretation.

I will leave the source SVG and PNG files in the PowerArube folder of this repo, and you can change as you see fit. Unfortunately, I have no more time to do customization at this time.

Hope this helps!

Cheers,
Adil

**Comment by alagoutte** [comment]
Thanks !
