### ISSUE TITLE
PowerShell Saturday Paris Logo

### ISSUE THREAD

**Issue by adilio** [adilio/ps-design#2]
Working with @lazywinadmin (FX) to design a PowerShell Saturday Paris logo/sticker. He would like something nice and simple, a relatively flat design. We have worked on a few mock-ups together.

**Comment by lazywinadmin** [comment]
cc: @omiossec @LaurentLienhard @stephanevg

**Comment by adilio** [comment]
These are some of the ideas thus far, as worked on with @lazywinadmin:

![ps-saturday-paris-simple](https://user-images.githubusercontent.com/21287462/60855368-3cf11e00-a1b8-11e9-9d94-73c4e8eba223.png)

And icon:
![ps-sat-logo-alternate2](https://user-images.githubusercontent.com/21287462/60855384-52664800-a1b8-11e9-8fe0-d47a2840f4f1.png)

This was original idea, but we both found it a bit too.... busy:
![ps-sat-paris](https://user-images.githubusercontent.com/21287462/60855410-6e69e980-a1b8-11e9-9102-bc728c4152c6.png)

**Comment by omiossec** [comment]
I like the last one

**Comment by Stephanevg** [comment]
I like the logo on icon. The ps Saturday one a bit less

**Comment by LaurentLienhard** [comment]
For the PS Saturday I like the last but without the face and maybe a little less yellow color for the logo

**Comment by adilio** [comment]
Hi All!

OK, so the original design (last one) was a bit too complicated. We can definitely mute colours and remove elements, but I'd encourage taking another look at the one at the top.

Remember that it will likely be shrunken down, and possibly be put on a sticker. Simplicity works better in those cases.

I'll leave you all to discuss, and come to a consensus. Once that's clear, we can proceed with one direction. Sound good?

Merci beaucoup!

**Comment by brettmillerb** [comment]
I think the logo needs to be like a light projecting the logo.....representing the light on top of the tower

**Comment by lazywinadmin** [comment]
I prefer the first one, simple and direct. PowerShell and Paris.
Any ideas on how it could be improved ?

**Comment by LaurentLienhard** [comment]
First one for me 👍

**Comment by adilio** [comment]
Hi All, yes I'm leaning towards first one as well.

Can work on enhancing it a bit.

I still feel like we could integrate a hashtag in there. SOmething like #PSSatParis ?

Please feel free to share ideas, Mes Amies!

**Comment by lazywinadmin** [comment]
Hey @adilio Thanks again for your help.
I think we will go with the first logo (powershell core logo with the yellow eiffel tower in it).
Would you have a large version ?

**Comment by adilio** [comment]
Of course @lazywinadmin !

Larger PNG is here in the repo at:
https://github.com/adilio/ps-design/blob/master/ps-saturday-paris/ps-saturday-paris-large.png

Larger scalable SVG is at:
https://github.com/adilio/ps-design/blob/master/ps-saturday-paris/ps-saturday-paris-large.svg

You can make that one as big as you like in InkScape (OSS).

Cheers! 🍻

**Comment by lazywinadmin** [comment]
Thank you sir! We own you one 👍 🍺

**Comment by adilio** [comment]
As the work is now complete on this, going to go ahead and close this issue. Cheers!
