### ISSUE TITLE
PSHTML Logo

### ISSUE THREAD

**Issue by Stephanevg** [adilio/ps-design#4]
Hi @adilio ,

I have just seen the logos you have created for our PSaturday and the for French Powershell UserGroup in general.

I actually really like your style, and would be curious to know if you be interested in desing a logo for [PSHTML,](https://github.com/Stephanevg/pshtml) so that it can have some better visibility.

Cheers

**Comment by adilio** [comment]
Hiya @Stephanevg!

Always willing to collab with a fellow PowerSHell'er!

I'm currently a bit behind with PS Conference Book, and changing jobs 😄.

Will reach out as soon as I have spare cycles. Feel free to drop in ideas and inspiration in this thread, in the interim!

**Comment by Stephanevg** [comment]
ok great. Looking forward to collaborate with you on this! :)

**Comment by adilio** [comment]
Hi @Stephanevg , just following up on this.

Did you have any ideas or inspiration that you'd like to provide? It'd be best if I had an idea of what you were going for, so that I can have a general direction. I can then draft up something, and we can go back and forth from there.

Looking forward to your feedback! 😃

**Comment by Stephanevg** [comment]
Hey @adilio 
I actually do (kind of)

![image](https://user-images.githubusercontent.com/6302961/62205181-2a20d200-b38f-11e9-82ed-a97738469bcd.png)

I was thinking of Something like that. But as you can see, my designers skills are really low. (and I tried to follow tutorials etc... * facepalm * :D XD )

**Comment by adilio** [comment]
This is great feedback and inspiration; thanks!

I will work on a draft of a few alternate styles. The nice thing is, you don't have to stick to only one. You can always have  alternate designs for stickers, header, dark/light background, etc.

I'll post back here once I have something to show.

**Comment by Stephanevg** [comment]
Great! Looking forward to it!

**Comment by Stephanevg** [comment]
Hey @adilio , did you had a chance to think of something already? (Sorry, I am really super excited about this one! 😸  🕺 🌟 )

**Comment by adilio** [comment]
Hi There @Stephanevg!

OK, so first pass, just came up with 2 ideas for design with background:

![pshtml](https://user-images.githubusercontent.com/21287462/63647464-a7add880-c6d6-11e9-971c-ea533690e6b1.png)

![pshtml-grey](https://user-images.githubusercontent.com/21287462/63647465-abd9f600-c6d6-11e9-9a7a-c943cf2df8ef.png)

The first one uses the blue from the original PS icon background, while the second uses the grey you originally referenced. I've added the same coloured shadow to the text as the original logo.

Shrinking the prompt from the original logo in the background to the new dimension does bend the corners in the strange way.

Let me know what you think, and any feedback or other ideas? Again this is a first dreaft, so we can change as much as we like.

Cheers!

**Comment by Stephanevg** [comment]
Great! Thank you so much for this first version @adilio 
Yeah, I think you got the spirit.
The gray color I had in my example was just for a test. There is no need to reuse that color. As a matter effect, I really prefer the blue color.

Concerning the logo, there are two things where I think we could make it better:
- Font
- Seperation between the word 'PS' and 'HTML'.

For the Font, I was looking in some 'pixel' fonts. (Something that would look a bit 'retro' 'video game' style. kind of like this perhaps -> https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwix4N3VtZ7kAhUMWxoKHSCNBfoQjRx6BAgBEAQ&url=https%3A%2F%2Fit.dreamstime.com%2Fillustrazione-di-stock-lettere-del-pixel-e-numeri-arrotondati-audaci-alfabeto-image64937947&psig=AOvVaw3fZ3A8US8DfaaJNiJBW6PO&ust=1566224835775019

- Seperation

Regarding the separation, I was perhaps thinking in putting the word PS in a Powershellprompt or so. The color was my way of separating them (but still keeping them in one word of course). But the color is actually not an obligation.

What do you think?

**Comment by adilio** [comment]
Heya @Stephanevg!

OK, I've decided to have a little fun with this one! 😁 

I like the idea of a flat material background that is a web page, with some hints of colour to make it pop a little. It is a bit of a departure from the first design, but I was inspired to take it in a bit of a different direction.

Hope you like it! Appreciate your feedback either way.

Cheers,
Adil

![pshtml1](https://user-images.githubusercontent.com/21287462/64471085-20338100-d13c-11e9-8a8e-0104d3899ca1.png)

**Comment by Stephanevg** [comment]
huu, i like that @adilio !!

I think we are getting there!
You think you could make the console smaller, and perhaps put it behind the 'PS' of PSHTML?

**Comment by adilio** [comment]
Heya @Stephanevg,

Sorry, I'm not following 😅.

Any chance you could clarify?

**Comment by adilio** [comment]
Heya @Stephanevg,

Thanks for explaining over Twitter!

I decided to use the background browser image behind the HTML part of the logo, since that part is lighter. Also, it suits the subject matter better, as the HTML is actually what's being rendered.

Two options for you:

![pshtml2](https://user-images.githubusercontent.com/21287462/65217252-59d38880-da68-11e9-890c-7f9f17707f76.png)

![pshtml3](https://user-images.githubusercontent.com/21287462/65217295-7e2f6500-da68-11e9-8157-160fc5d8d69f.png)

Cheers!

**Comment by adilio** [comment]
Another option as well, based on our discussion:

![pshtml4](https://user-images.githubusercontent.com/21287462/65218058-7a9cdd80-da6a-11e9-80e3-0b7d57f5afb5.png)

**Comment by Stephanevg** [comment]
ok cool thanks @adilio I'll bring this to a vote on the French channel. We will see ;)

**Comment by adilio** [comment]
Hey @Stephanevg , hope you're well?

Still hoping you could put the comments from Twitter DM into this issue. Currently at a conference, but will check back here shortly.

**Comment by adilio** [comment]
OK, one more try 😄 .

Here's a version without the console background, and in the MS Segoe UI font.

![pshtml5](https://user-images.githubusercontent.com/21287462/65819258-3c708e00-e1cf-11e9-803d-94dd6578e304.png)

Updated PNG and SVG are in the repo.

Lemme know if that works for you!
Cheers! 🍻

**Comment by adilio** [comment]
As per discussion with @Stephanevg over Twitter DM, this issue is now closed 😄.
