### ISSUE TITLE
Private Commission

### ISSUE THREAD

**Issue by brettmillerb** [adilio/ps-design#5]
@adilio you legend.

Can't remember how much we discussed but I was gonna ask for an Accidental DBA sticker.

Obviously I would like hex buy the non uniform word lengths may not be a good fit for a geometric hexagon

I looked at other DBA type logos and like the database symbol but happy to toss some ideas about.

Or this type in a hex? I literally have no idea how to represent it without just having the words and a database logo.

This is why I don't design things.

![SQL UG logo](https://i0.wp.com/sqlglasgow.co.uk/wp-content/uploads/2017/10/cropped-sql-glasgow-logo-TEMP_SQL-Glasgow.png)

**Comment by adilio** [comment]
Heya @brettmillerb,

For Sure! Sounds like a plan, I will start playing with a design.

Just trying to wrap up a few more earlier issues, but will post here once I have a draft ready.

You Rock! 🤟

**Comment by adilio** [comment]
Heya Brett,

Just putting a first draft our there for the Accidental DBA sticker.

The two images I wanted to incorporate into the DBA logo were a fire, and possible a car crash.

Here's what I've come up with so far.

Please provide feedback, Broski. Cheers!

![accidental-dba](https://user-images.githubusercontent.com/21287462/62182176-8097fd00-b30a-11e9-9c1d-3cffc39e0f35.png)

![accidental-dba-2](https://user-images.githubusercontent.com/21287462/62182179-84c41a80-b30a-11e9-9b01-2fe1776cd3ef.png)

**Comment by vexx32** [comment]
@adilio gotta make it look _slightly_ more like an oil drum for maximum impact 😉

**Comment by brettmillerb** [comment]
Bit busy, what about maybe the see no evil emoji with accidental DBA underneath and the database logo inline with the text.

![seenoevil monkey](https://emojis.wiki/emoji-pics/microsoft/see-no-evil-monkey-microsoft.png)

Was just thinking a die cut would work that way. Not sure having two images would though.

**Comment by brettmillerb** [comment]
Or the database logo with accidental DBA going through it akin to this.

![die cut sticker](https://folkhogan.com/wp-content/uploads/IMG_8150-e1495038043647.jpg)

Thinking of people's laptop real estate and keeping it compact.

**Comment by bobfrankly** [comment]
> Bit busy, what about maybe the see no evil emoji with accidental DBA underneath and the database logo inline with the text.
> 
> ![seenoevil monkey](https://camo.githubusercontent.com/e5d9fa89c1a5798095225013f0664a2da9c74eae/68747470733a2f2f656d6f6a69732e77696b692f656d6f6a692d706963732f6d6963726f736f66742f7365652d6e6f2d6576696c2d6d6f6e6b65792d6d6963726f736f66742e706e67)
> 
> Was just thinking a die cut would work that way. Not sure having two images would though.

Flip the smile and replace the tounge with teeth. Accidental DBA is rarely something to smile about XD

**Comment by adilio** [comment]
Take 2:

![accidental-dba-monkeys](https://user-images.githubusercontent.com/21287462/63647941-2b6ac380-c6dd-11e9-8657-51e69dd934c3.png)

The single monkey looked a little lonely in the middle, so I brought his friends along. Looks cool, but will likely need more tweaking.

Thoughts?

**Comment by brettmillerb** [comment]
I like it......I think it needs "accidental DBA" in it though for significance 😋

I won't pretend to have any design ideas above my station.

**Comment by adilio** [comment]
OK, I think we're getting close!

I revised it again to simplify, using just the one monkey, in a slightly flatter style. I've included the text, and I've created a happy and sad version.

Lemme know what you think. Ship it? 🚀 

![accidental-dba-monkey-sad](https://user-images.githubusercontent.com/21287462/63906924-649d7f00-c9ce-11e9-889f-e57c83106609.png)
![accidental-dba-monkey-happy](https://user-images.githubusercontent.com/21287462/63906925-649d7f00-c9ce-11e9-9737-15b182a5c2c5.png)

**Comment by brettmillerb** [comment]
just reminded me about this 😄

**Comment by adilio** [comment]
Here you go!

![accidental-dba-monkey-sad](https://user-images.githubusercontent.com/21287462/64470626-62889e00-d0fb-11e9-9397-c962bb8814ba.png)

**Comment by adilio** [comment]
Closing this off as complete!

Cheers1 🍻

**Comment by brettmillerb** [comment]
Cheers @adilio, top work 👍
