### ISSUE TITLE
Planet PowerShell

### ISSUE THREAD

**Issue by kjacobsen** [adilio/ps-design#6]
Wanted to start of by saying I love the design work you did for PSScriptAnalyzer.

I was wondering if you might be able to help develop a better logo for [Planet PowerShell](https://planetpowershell.com). The current logo was me spending a few minutes in GIMP before I launched the service.

**Comment by adilio** [comment]
Hi @kjacobsen,

Thanks for reaching out!

Yeah, we could for sure work on something together!

Please provide some general ideas or inspiration, for me to start a draft with.

I have a couple of issues to address first, but I will for sure get back to you as soon as I have time to work on this.

Cheers

**Comment by adilio** [comment]
Heya @kjacobsen , just following-up.

Haven't heard back from you regarding ideas, so I had a crack at a first draft. Feedback is much appreciated!

Cheers,
Adil

![planet-powershell](https://user-images.githubusercontent.com/21287462/62187749-3a996400-b31f-11e9-9124-908e5128f41a.png)

**Comment by kjacobsen** [comment]
That looks really good!! I really like the PowerShell logo over the globe. I am just not sure about the Ps.

Perhaps a simple Planet PowerShell along the bottom?

**Comment by adilio** [comment]
Gotcha. Will look into this shorty.

**Comment by adilio** [comment]
Hi @kjacobsen, sorry for the delay! I've been tied up with training for a new position.

I've created multiple versions of the logo: one with black text, one with white text, and one that is just the logo.

All versions are available at: https://github.com/adilio/ps-design/tree/master/planet-powershell

I'm including samples here:

![planet-powershell-logo](https://user-images.githubusercontent.com/21287462/63074433-dbc51480-bef2-11e9-9ffb-c8dbe3d62856.png)

![planet-powershell-black-text](https://user-images.githubusercontent.com/21287462/63074483-19c23880-bef3-11e9-9285-5d4edc8157bf.png)

![planet-powershell-white-text](https://user-images.githubusercontent.com/21287462/63074445-f4cdc580-bef2-11e9-9c82-64fd65bd227d.png)

Cheers! 🍻

**Comment by kjacobsen** [comment]
Hi,

Sorry for the delay.

They look awesome!!!! LOVE YOUR WORK!
