### ISSUE TITLE
Prague PowerShell meetup logo

### ISSUE THREAD

**Issue by nohwnd** [adilio/ps-design#7]
I'd like to ask you to help me develop a logo for PowerShell meetup in Prague.

I think it would be worth to explore the idea of the standard PowerShell logo, with the czech flag, because the wedge fits nicely with the > in powershell. Something like the abomination here, but with nicer colors and the >_ coming out of it a bit more: 
![image](https://user-images.githubusercontent.com/5735905/61443038-069a6800-a949-11e9-978e-fc14232cdce5.png)

What do you think? I am open to any suggestions, or a change of direction entirely, I would just like to avoid outline of Prague castle in the logo :D

**Comment by adilio** [comment]
Hi @nohwnd,

Thanks for reaching out!
Yeah, doesn’t look too tricky, and the simpler the better.
I have a couple of issues to address first, but I will for sure get back to you as soon as I have time to work on this.
Cheers

**Comment by adilio** [comment]
Hi @nohwnd!

Congrats on the sponsorship, btw! Well-deserved! Keep being awesome!

Here's my first take on your design. Used the CZ colours from the Wikipedia flag image. Hope that's ok.

Also, used the original PS logo colour as the background. Belnds in a bit, but I like that it is subtle.

![prague-ps](https://user-images.githubusercontent.com/21287462/63648241-acc45500-c6e1-11e9-875c-d45d0bb3fea5.png)

**Comment by nohwnd** [comment]
Thanks, that looks great :)

**Comment by adilio** [comment]
Cool!

I've updated the files in: https://github.com/adilio/ps-design/tree/master/prague-psug

The vector should be in there too, in case you need to make it bigger or smaller. I really like the simplicity! 😁

**Comment by adilio** [comment]
Closing now, as files completed and uploaded to repo.
