### ISSUE TITLE
Denver User Group logo

### ISSUE THREAD

**Issue by markroloff** [adilio/ps-design#8]
Hey @adilio,

Hope the chapter is coming along nicely and definitely looking forward to reading it when the book comes out.

Getting this on your radar per our quick chat.

@joeypiccola, @mcdeo1996, and I are putting the Denver group through some metamorphosis and thought a logo that would also work well as a sticker would be a fun addition. Vague ideas at this point but hopefully enough to start a dialogue with.

Denver has a pretty iconic skyline with the mountains as a backdrop, so we're definitely interested in ways that it can be incorporated with the PS logo. [This Google image search](https://www.google.com/search?q=denver+skyline+silhouette+mountains&rlz=1C1OKWM_enUS780US780&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiJyN6ci8XjAhVReKwKHS_7ByoQ_AUIESgB&biw=1920&bih=947) has plenty of examples.

Couple different color schemes in mind...
1. Earthy tones and colors generally associated with the Colorado outdoors. An example of this is some of the work done by a local artist, [Atomic Child](http://www.atomicchild.com/store?category=Stickers).
2. Pinks and purples are pretty common in our sunsets, so a vapor/synthwave scheme could also be cool.

**Comment by adilio** [comment]
Heya @markroloff  Denver Crew!

For sure, I am on the lookout for some good base designs, and the skyline aspect is cool. I want to be careful to only use images that are labeled for reuse, as well as icon sites for which I have a Premium/Tools membership.

I also like the Earth tones from Atomic Child, great inspiration.

I will keep looking and work on a draft soon. Just a few projects in the queue here, so I wan to make sure to address in an orderly fashion.

I'm excited! Stay tuned!

**Comment by adilio** [comment]
Here you go! Had to change the perspective on the skyline a bit, in order to fit the circle pattern.

Let me know if that works!

Cheers,
Adil

![denver-skyline-mountains-round1](https://user-images.githubusercontent.com/21287462/64470600-b941a800-d0fa-11e9-8607-50eeb9c7a12b.png)

![denver-skyline-mountains-round2](https://user-images.githubusercontent.com/21287462/64470601-b941a800-d0fa-11e9-8d18-a8e5928e2d47.png)

**Comment by markroloff** [comment]
That second one looks nice!

Couple ideas from people that are being stubborn about posting in here 😜 

1. Can we try replacing the concentric circles in the middle with a "C", similar to the Colorado flag?
2. How would a color palette matching the state colors (red, white, blue, yellow) look?

**Comment by adilio** [comment]
Heya Mark,

I will try to get to this when I can, but I'd urge that we shouldn't complicate the design too much. May just come off looking a bit busy.

I'll give it one more round of tweaks though, and come back with something I hope you like. Sound good?

Cheers!

**Comment by adilio** [comment]
Heya @markroloff, as discussed, closing this off for now. Totally happy to revisit if you'd like to come back and try some stuff together! Keep on doing awesome stuff in the PowerShell Community! Mulch Love! ❤️
